version: '3.8'

services:
  cloudflare-updater:
    build:
      context: .
    pull_policy: build
    image: cloudflare-updater:latest
    container_name: cloudflare-updater
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default
    volumes:
      - ./app:/app

networks:
  nginx-proxy-manager_default:
    external: true