version: '3.8'

services:
  cloudflare-updater:
    build:
      context: .
      args:
        - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
        - ZONE_ID=${ZONE_ID}
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      ZONE_ID: ${ZONE_ID}
    pull_policy: build
    image: cloudflare-updater:latest
    container_name: cloudflare-updater
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true